name: MAP573
channels:
  - conda-forge
dependencies:
#  - graph-tool
#  - jupytext
  - numpy
  - matplotlib
  - scikit-learn
  - pandoc
  - r-aricode
  - r-base=3.6.3
  - r-corrplot
  - r-devtools
  - r-dt
  - r-codetools
  - r-foreign
  - r-ggally
  - r-igraph
  - r-knitr
  - r-learnr
  - r-matrix
  - r-maps
  - r-readods
  - r-rcpp
  - r-rcpparmadillo
  - r-reticulate
  - r-rmarkdown
  - r-tidyverse
